### PR TITLE
Temporary disable visual tests

### PR DESCRIPTION
**Pull request by limonte**
> @jouni:
> IMO we should remove/disable the visual tests until we reach a beta candidate for the themes. Until then, we need to test it manually and listen to user feedback if some things are broken.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-themes/24)

### CODE REVIEW

**Comment by jouni** [comment]
I don’t understand the Travis config at all, but otherwise I approve this change :)

**Comment by manolo** [comment]
Id we don't have any tests run in CI, I guess we could disable the CI build instead. I think linter is already checked in local IDE.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/24#-:-KnrXUb6HiIaiiBKTn4_:b-jau1gh)*

**Comment by manolo** [comment]
Anyways, this PR fails in CI, so probably someone is pushing without linting changes.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/24#-:-KnrXtmjPyiuZU9meLsD:bnyqak)*

**Comment by jouni** [comment]
> Anyways, this PR fails in CI, so probably someone is pushing without linting changes.

That’s me, pretty sure, sorry. I didn’t really pay attrntion to this fact, I didn’t realize I need to run the linter.

**Comment by jouni** [comment]
I’ll try to run them today and fix all issues.

**Comment by jouni** [comment]
:lgtm: (I assume this Travis config change is fine, as no one has commented on it)

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/24#-:-KnsF5BAMY3DR6aE2swG:b-y43kyr)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/24)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/24#-:-KntufsnqGRL0YbdeQj0:bnfp4nl)*

**Pull request merged**
