### PR TITLE
Add vaadin-text-field focused attribute to visual tests

### PR DESCRIPTION
**Pull request by samiheikki**
Connects to #3

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-themes/13)

### CODE REVIEW

**Comment by jouni** [comment]
The current material.html import doesn’t import any element themes, only the global stuff.

We should add a bundle import file, like material-with-all-elements.html and use that in the visual tests. It might be even better to import individual element files in the tests instead, so we can be sure there aren’t any accidental dependencies between element themes.

**Comment by jouni** [comment]
Just to add, the screenshots in this PR are invalid because the theme for text field is not imported.

**Comment by jouni** [comment]
Also, we talked about not adding visual test before the beta stage. It might be faster to work without thise during early development, and then build up the testsduring the beta period when we know we should not be making any breaking changes anymore.

So it might be better to just remove/disable all visual tests for now.

**Comment by samiheikki** [comment]
Good points @jouni. I'll close this PR and make another that removes the tests be runned by travis for now.

**Pull request closed without merging**
