### PR TITLE
Initial valo theme for grid with demo

### LINKED ISSUE #42: Initial Valo theme for <vaadin-grid>
Specs from https://app.zeplin.io/project/5937d86d3601d452f1b8e66a

Note that styling the checkbox is not part of this task!

### PR DESCRIPTION
**Pull request by yuriy-fix**
Fixes #42 
Initial valo theme for grid with demo

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-themes/43)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Somehow the header content seems to have different `color` than the body (tested in bakery app)

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[bower.json, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-KscKNNs1h0gsMjw10QR:-KscKNNs1h0gsMjw10QS:b-a2zuz6) ([raw file](https://github.com/vaadin/vaadin-themes/blob/ea50708a872e7e9798772a72d5d58ca74386646e/bower.json#L29)):*
> ```JSON
>   "devDependencies": {
>     "web-component-tester": "^6.0.0",
>     "vaadin-grid": "vaadin/vaadin-grid#valo-grid",
> ```

Rather apply the padding change to "4.0-preview" and target that here.

---

*[valo/vaadin-grid.html, line 19 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-KscLTVme-8zs7xdpVVs:-KscLTVme-8zs7xdpVVt:b-t2j1i2) ([raw file](https://github.com/vaadin/vaadin-themes/blob/ea50708a872e7e9798772a72d5d58ca74386646e/valo/vaadin-grid.html#L19)):*
> ```HTML
>       [part~="header-cell"],
>       [part~="footer-cell"] {
>         background: var(--valo-base-color);
> ```

Why are these properties only applied to header/footer cells?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-:-KscN9rZMs7SpjzP0SVg:b-hsi5h2)*

**Comment by YuriyVaadin** [comment]
Reviewed 2 of 2 files at r2.
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[bower.json, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-KscKNNs1h0gsMjw10QR:-KscWGC-J4QoLHo5KCnC:b-896fix) ([raw file](https://github.com/vaadin/vaadin-themes/blob/ea50708a872e7e9798772a72d5d58ca74386646e/bower.json#L29)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Rather apply the padding change to "4.0-preview" and target that here.
</blockquote></details>

Done.

---

*[valo/vaadin-grid.html, line 19 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-KscLTVme-8zs7xdpVVs:-KscWH36-wGFkMCykV66:bb9wx1b) ([raw file](https://github.com/vaadin/vaadin-themes/blob/ea50708a872e7e9798772a72d5d58ca74386646e/valo/vaadin-grid.html#L19)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why are these properties only applied to header/footer cells?
</blockquote></details>

Background is applied to all cells now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43)*

**Comment by tomivirkki** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[valo/vaadin-grid.html, line 19 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-KscLTVme-8zs7xdpVVs:-Kscedyw6pVUwtQMTNXm:b-d3rin2) ([raw file](https://github.com/vaadin/vaadin-themes/blob/ea50708a872e7e9798772a72d5d58ca74386646e/valo/vaadin-grid.html#L19)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Background is applied to all cells now.
</blockquote></details>

What about font-family? Shouldn't that also apply?

---

*[valo/vaadin-grid.html, line 10 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-Kscf9qWyQibinSy_Dae:-Kscf9qWyQibinSy_Daf:b-wfnvdw) ([raw file](https://github.com/vaadin/vaadin-themes/blob/bf007516bad35563c7d9604f937b078af721f3df/valo/vaadin-grid.html#L10)):*
> ```HTML
>     <style>
>       :host {
>         border: 1px solid var(--valo-shade-10pct);
> ```

This should use contrast also

---

*[valo/vaadin-grid.html, line 41 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-KscfVAWf7o-1rjI-_Up:-KscfVAWf7o-1rjI-_Uq:bbxc4ue) ([raw file](https://github.com/vaadin/vaadin-themes/blob/bf007516bad35563c7d9604f937b078af721f3df/valo/vaadin-grid.html#L41)):*
> ```HTML
> 
>       [part~="row"][selected] [part~="body-cell"] {
>         background: var(--valo-shade-10pct);
> ```

Should this use shade or contrast?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43)*

**Comment by YuriyVaadin** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[valo/vaadin-grid.html, line 19 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-KscLTVme-8zs7xdpVVs:-KscwJL6IW2E0CE5IAEY:bscequx) ([raw file](https://github.com/vaadin/vaadin-themes/blob/ea50708a872e7e9798772a72d5d58ca74386646e/valo/vaadin-grid.html#L19)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

What about font-family? Shouldn't that also apply?
</blockquote></details>

Font-family and color are applied for all cells as well now.

---

*[valo/vaadin-grid.html, line 10 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-Kscf9qWyQibinSy_Dae:-KscwVMAPn4CKNhEvR4a:b-2w4dij) ([raw file](https://github.com/vaadin/vaadin-themes/blob/bf007516bad35563c7d9604f937b078af721f3df/valo/vaadin-grid.html#L10)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This should use contrast also
</blockquote></details>

Using contrast now.

---

*[valo/vaadin-grid.html, line 41 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-KscfVAWf7o-1rjI-_Up:-KscwT9V0RENk-oPeMbD:b-2w4dij) ([raw file](https://github.com/vaadin/vaadin-themes/blob/bf007516bad35563c7d9604f937b078af721f3df/valo/vaadin-grid.html#L41)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Should this use shade or contrast?
</blockquote></details>

Using contrast now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43)*

**Comment by tomivirkki** [comment]
*[valo/vaadin-grid.html, line 19 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-KscLTVme-8zs7xdpVVs:-Ksd4W0q_N1C8MbppEXD:b-h0cm2p) ([raw file](https://github.com/vaadin/vaadin-themes/blob/ea50708a872e7e9798772a72d5d58ca74386646e/valo/vaadin-grid.html#L19)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Font-family and color are applied for all cells as well now.
</blockquote></details>

Shouldn't cells also have font-size and line-height affected by Valo?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43)*

**Comment by tomivirkki** [comment]
Review status: 1 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[demo/valo/grids.html, line 48 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-KsgkrmlhV8tgbET2oDP:-KsgkrmlhV8tgbET2oDQ:b-984hjp) ([raw file](https://github.com/vaadin/vaadin-themes/blob/a3174c1c489e2c67235045576ea747747448bbf9/demo/valo/grids.html#L48)):*
> ```HTML
>           <template is="dom-bind">
>             
>             <iron-ajax auto url="https://demo.vaadin.com/demo-data/1.0/people?count=200" handle-as="json" last-response="{{users}}"></iron-ajax>
> ```

If you're using `<iron-ajax>` in the demo, it should be included in devDependencies

---

*[demo/valo/grids.html, line 53 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-KsgjmmiacEaRVbNCn2V:-KsgjmmiacEaRVbNCn2W:b2orf1j) ([raw file](https://github.com/vaadin/vaadin-themes/blob/a3174c1c489e2c67235045576ea747747448bbf9/demo/valo/grids.html#L53)):*
> ```HTML
>             <vaadin-grid aria-label="Basic Binding Example" items="[[users.result]]">
> 
>               <vaadin-grid-column width="50px" flex-grow="0">
> ```

The demos don't look right: https://www.dropbox.com/s/f9tg2hyh7a5hfbb/Screenshot%202017-08-29%2009.46.12.png?dl=0

At least the index column needs to be wider and the grid could have some top margin so that the button would be visible

---

*[demo/valo/grids.html, line 62 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-Ksgl07Jopa30vocAVoU:-Ksgl07Jopa30vocAVoV:bwm7ndb) ([raw file](https://github.com/vaadin/vaadin-themes/blob/a3174c1c489e2c67235045576ea747747448bbf9/demo/valo/grids.html#L62)):*
> ```HTML
>               <vaadin-grid-column>
>                 <template class="header">
>                   <span draggable="true">
> ```

Why draggable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43)*

**Comment by manolo** [comment]
Tried this branch with bakery:
- Header is not shown at all. It seems a problem in the grid 4.0-preview, but we need headers to see whether the theme works, so this should be merged after it's fixed.
- row height is apparently 58px since the design for bakery (zeplin.io) says 48px, not sure what is the spec for valo but I think it should be what bakery app design shows.
- header height of valo theme probably should be 64px like it is shown in bakery designs instead of 53px

---

Review status: 1 of 4 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-:-KsgjH7ybg4PWU6d2ukk:b-pd6to0)*

**Comment by YuriyVaadin** [comment]
- Row height is changed.
- Header height is also changed.

---

Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[demo/valo/grids.html, line 48 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-KsgkrmlhV8tgbET2oDP:-Ksgu75TQtBOE4Q2Llfj:bqmjwcz) ([raw file](https://github.com/vaadin/vaadin-themes/blob/a3174c1c489e2c67235045576ea747747448bbf9/demo/valo/grids.html#L48)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

If you're using `<iron-ajax>` in the demo, it should be included in devDependencies
</blockquote></details>

Added.

---

*[demo/valo/grids.html, line 53 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-KsgjmmiacEaRVbNCn2V:-KsguBNFGkaPkTgel8oy:b-a2ujfl) ([raw file](https://github.com/vaadin/vaadin-themes/blob/a3174c1c489e2c67235045576ea747747448bbf9/demo/valo/grids.html#L53)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The demos don't look right: https://www.dropbox.com/s/f9tg2hyh7a5hfbb/Screenshot%202017-08-29%2009.46.12.png?dl=0

At least the index column needs to be wider and the grid could have some top margin so that the button would be visible
</blockquote></details>

Changed.

---

*[demo/valo/grids.html, line 62 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-Ksgl07Jopa30vocAVoU:-KsguDEeDGZly_nOhIDg:bss4a2b) ([raw file](https://github.com/vaadin/vaadin-themes/blob/a3174c1c489e2c67235045576ea747747448bbf9/demo/valo/grids.html#L62)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why draggable?
</blockquote></details>

Removed.

---

*[valo/vaadin-grid.html, line 19 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-KscLTVme-8zs7xdpVVs:-KsguEzTbcpfO96FLS69:b9n8t15) ([raw file](https://github.com/vaadin/vaadin-themes/blob/ea50708a872e7e9798772a72d5d58ca74386646e/valo/vaadin-grid.html#L19)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Shouldn't cells also have font-size and line-height affected by Valo?
</blockquote></details>

Defined for all cells now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-:-KsguJvjZsuQyduRyNY8:b-h0czdh)*

**Comment by tomivirkki** [comment]
*[demo/valo/grids.html, line 53 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-KsgjmmiacEaRVbNCn2V:-KsgxyFL9ImzeUnvT2Dz:b-o3grne) ([raw file](https://github.com/vaadin/vaadin-themes/blob/a3174c1c489e2c67235045576ea747747448bbf9/demo/valo/grids.html#L53)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Changed.
</blockquote></details>

For the other grid also

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43)*

**Comment by YuriyVaadin** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[demo/valo/grids.html, line 53 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-KsgjmmiacEaRVbNCn2V:-KsgyJJMEEVVyRyRs82s:b-896fix) ([raw file](https://github.com/vaadin/vaadin-themes/blob/a3174c1c489e2c67235045576ea747747448bbf9/demo/valo/grids.html#L53)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

For the other grid also
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43)*

**Comment by tomivirkki** [comment]
Review status: 0 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[valo/vaadin-grid.html, line 14 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-Ksh0trrKSRQUIrW3ZvS:-Ksh0trscAKheT_LeQIp:b5gli9) ([raw file](https://github.com/vaadin/vaadin-themes/blob/a4b44437a8877605d11eb181770b6f92135a8eab/valo/vaadin-grid.html#L14)):*
> ```HTML
> 
>       [part~="cell"] {
>         padding: calc(var(--valo-size-l)/4) var(--valo-space-m);
> ```

Paddings should be based on `--valo-space`s only (not -size).

---

*[valo/vaadin-grid.html, line 24 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-Ksh18Nhwmqp6KxUNANt:-Ksh18Nhwmqp6KxUNANu:b5gli9) ([raw file](https://github.com/vaadin/vaadin-themes/blob/a4b44437a8877605d11eb181770b6f92135a8eab/valo/vaadin-grid.html#L24)):*
> ```HTML
>       [part~="header-cell"],
>       [part~="footer-cell"] {
>         padding: calc(var(--valo-size-l)/2 - var(--valo-space-xs)/4) var(--valo-space-m);
> ```

Paddings should be based on `--valo-space`s only (not -size).

---

*[valo/vaadin-grid.html, line 26 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-Ksh-HECslmKDdmVEs9s:-Ksh-HECslmKDdmVEs9t:b-l6mwxj) ([raw file](https://github.com/vaadin/vaadin-themes/blob/a4b44437a8877605d11eb181770b6f92135a8eab/valo/vaadin-grid.html#L26)):*
> ```HTML
>         padding: calc(var(--valo-size-l)/2 - var(--valo-space-xs)/4) var(--valo-space-m);
>         font-size: var(--valo-font-size, var(--valo-font-size-xs));
>         line-height: var(--valo-line-height);
> ```

remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43)*

**Comment by YuriyVaadin** [comment]
Review status: 0 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[valo/vaadin-grid.html, line 14 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-Ksh0trrKSRQUIrW3ZvS:-KshBKWP0v06kvocv8-B:b-896fix) ([raw file](https://github.com/vaadin/vaadin-themes/blob/a4b44437a8877605d11eb181770b6f92135a8eab/valo/vaadin-grid.html#L14)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Paddings should be based on `--valo-space`s only (not -size).
</blockquote></details>

Done.

---

*[valo/vaadin-grid.html, line 24 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-Ksh18Nhwmqp6KxUNANt:-KshBLe2jKsCZYgt6dXU:b-ns1yp4) ([raw file](https://github.com/vaadin/vaadin-themes/blob/a4b44437a8877605d11eb181770b6f92135a8eab/valo/vaadin-grid.html#L24)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Paddings should be based on `--valo-space`s only (not -size).
</blockquote></details>

Done and applied for all cells.

---

*[valo/vaadin-grid.html, line 26 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-Ksh-HECslmKDdmVEs9s:-KshBNWQpLSSa24AOcsg:bss4a2b) ([raw file](https://github.com/vaadin/vaadin-themes/blob/a4b44437a8877605d11eb181770b6f92135a8eab/valo/vaadin-grid.html#L26)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43)*

**Comment by tomivirkki** [comment]
*[valo/vaadin-grid.html, line 26 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-Ksh-HECslmKDdmVEs9s:-KshNhb-Urevx7AeNtpV:bnvlz9n) ([raw file](https://github.com/vaadin/vaadin-themes/blob/a4b44437a8877605d11eb181770b6f92135a8eab/valo/vaadin-grid.html#L26)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Removed.
</blockquote></details>

No it's not :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43)*

**Comment by tomivirkki** [comment]
Few more issues: Try the Valo theme in the `<vaadin-grid>` demos. Especially columns.html:
- Column resize handle is invisible
- Column reordering has no styles at all
- Frozen columns separator isn’t visible

Don't fix these by including the default theme but adding more styles to the Valo theme module

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-:-KshQK-za9FD32F8YlGk:b-lb46vi)*

**Comment by samiheikki** [comment]
Reviewed 1 of 4 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[demo/valo/grids.html, line 154 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-KshuU4-dSoQY2Mk1Vu9:-KshuU4-dSoQY2Mk1VuA:b-8akhln) ([raw file](https://github.com/vaadin/vaadin-themes/blob/d2ffb0c3e8aec22785ad63a5d9f9378c2f6c03ff/demo/valo/grids.html#L154)):*
> ```HTML
>     </nice-demo-snippet>
> ```

Remove extra empty lines

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43)*

**Comment by YuriyVaadin** [comment]
Review status: 3 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[demo/valo/grids.html, line 154 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43#-KshuU4-dSoQY2Mk1Vu9:-KsiAA8l0eAxeJ71LvEY:b-896fix) ([raw file](https://github.com/vaadin/vaadin-themes/blob/d2ffb0c3e8aec22785ad63a5d9f9378c2f6c03ff/demo/valo/grids.html#L154)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Remove extra empty lines
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/43)*

**Pull request merged**
