### PR TITLE
Add valo themes for form-layout and form-item

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Valo themes for form-layout and form-item

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-themes/29)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/valo/common.html, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-themes/29#-KptQqWTPP50LJqFVbVx:-KptQqWTPP50LJqFVbVy:b-5zim16) ([raw file](https://github.com/vaadin/vaadin-themes/blob/b7fbf168d207259f4b1036afc91158821c0e807c/demo/valo/common.html#L13)):*
> ```HTML
>     {name: 'date-pickers', title: 'Date pickers'},
>     {name: 'text-fields', title: 'Text fields'},
>     {name: 'form-items', title: 'Form items'}
> ```

maybe `forms` instead

---

*[valo/vaadin-form-item.html, line 21 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-themes/29#-KptR7Os3MML1FUXc1ch:-KptR7Os3MML1FUXc1ci:bskja2m) ([raw file](https://github.com/vaadin/vaadin-themes/blob/b7fbf168d207259f4b1036afc91158821c0e807c/valo/vaadin-form-item.html#L21)):*
> ```HTML
>         margin-bottom: 0.5em;
>         transition: color 0.4s;
>         line-height: 1.333;
> ```

could those magic numbers being computed based on valo vars? 
Please take a look to other elements about magic numbers

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/29)*

**Comment by YuriyVaadin** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/valo/common.html, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-themes/29#-KptQqWTPP50LJqFVbVx:-Kptaj8zTniND4hhVGT2:b-896fix) ([raw file](https://github.com/vaadin/vaadin-themes/blob/b7fbf168d207259f4b1036afc91158821c0e807c/demo/valo/common.html#L13)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

maybe `forms` instead
</blockquote></details>

Done.

---

*[valo/vaadin-form-item.html, line 21 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-themes/29#-KptR7Os3MML1FUXc1ch:-KptaluYyUA-U7axIfPf:byxempb) ([raw file](https://github.com/vaadin/vaadin-themes/blob/b7fbf168d207259f4b1036afc91158821c0e807c/valo/vaadin-form-item.html#L21)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

could those magic numbers being computed based on valo vars? 
Please take a look to other elements about magic numbers
</blockquote></details>

The same values were used for part label in text-field. If Jouni allows me, I am able to replace them with similar vars or create new vars.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/29)*

**Comment by manolo** [comment]
Reviewed 1 of 6 files at r1, 1 of 7 files at r2.
Review status: 2 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[demo/valo/forms.html, line 63 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-themes/29#-Kpx_n4EC_hgW2SMo8a6:-Kpx_n4EC_hgW2SMo8a7:b-jjhpau) ([raw file](https://github.com/vaadin/vaadin-themes/blob/f2d883985b347c75b4c74b9e331c0be25c750546/demo/valo/forms.html#L63)):*
> ```HTML
>     </nice-demo-snippet>
> 
>   </div>
> ```

Add demos for 
- form-layout defining label position
- form-layout with pure vaadin components, (no vaadin-form-item wrapped), mixing all of them (date-picker, combo-box, etc)

---

*[valo/vaadin-date-picker.html, line 43 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-themes/29#-KpxaI8ZyRugXeBSLJ-z:-KpxaI8ZyRugXeBSLJ0-:bajwa7x) ([raw file](https://github.com/vaadin/vaadin-themes/blob/f2d883985b347c75b4c74b9e331c0be25c750546/valo/vaadin-date-picker.html#L43)):*
> ```HTML
>       }
> 
>       /* Will be implemented after adding this icon to vaadin-date-picker-icons */
> ```

Is there a PR with this already, otherwise we need to do first and not leave this here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/29)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 6 files at r1, 6 of 7 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[valo/vaadin-form-item.html, line 21 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-themes/29#-KptR7Os3MML1FUXc1ch:-Kpyi_z3KBHC1A14Z-Sf:b8538go) ([raw file](https://github.com/vaadin/vaadin-themes/blob/b7fbf168d207259f4b1036afc91158821c0e807c/valo/vaadin-form-item.html#L21)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

The same values were used for part label in text-field. If Jouni allows me, I am able to replace them with similar vars or create new vars.
</blockquote></details>

Let's do it in a separated PR when we ask him.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/29#-:-KpyijmJ3kQifEbT3qEj:bnfp4nl)*

**Comment by YuriyVaadin** [comment]
Review status: 5 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/valo/forms.html, line 63 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-themes/29#-Kpx_n4EC_hgW2SMo8a6:-Kq2Zk9dvCGSd5_0AUox:b-896fix) ([raw file](https://github.com/vaadin/vaadin-themes/blob/f2d883985b347c75b4c74b9e331c0be25c750546/demo/valo/forms.html#L63)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Add demos for 
- form-layout defining label position
- form-layout with pure vaadin components, (no vaadin-form-item wrapped), mixing all of them (date-picker, combo-box, etc)
</blockquote></details>

Done.

---

*[valo/vaadin-date-picker.html, line 43 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-themes/29#-KpxaI8ZyRugXeBSLJ-z:-Kq2ZlD1IeIyDbQZpwxy:b-896fix) ([raw file](https://github.com/vaadin/vaadin-themes/blob/f2d883985b347c75b4c74b9e331c0be25c750546/valo/vaadin-date-picker.html#L43)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Is there a PR with this already, otherwise we need to do first and not leave this here
</blockquote></details>

Done.

---

*[valo/vaadin-form-item.html, line 21 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-themes/29#-KptR7Os3MML1FUXc1ch:-Kq2ZnSbRJSvFlamv8uT:b2nhll9) ([raw file](https://github.com/vaadin/vaadin-themes/blob/b7fbf168d207259f4b1036afc91158821c0e807c/valo/vaadin-form-item.html#L21)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Let's do it in a separated PR when we ask him.
</blockquote></details>

Ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/29)*

**Comment by limonte** [comment]
Awesome! :lgtm: 

---

Reviewed 1 of 6 files at r1, 5 of 7 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/29#-:-Kq2pOHrrBcCITOpp6Pr:b-i581jd)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 7 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-themes/29#-:-Kq37EDvTDLFBdW4Qn2T:bnfp4nl)*

**Pull request merged**
